// app/models/contributions.js

var mongoose		= require('mongoose');
var Schema			= mongoose.Schema;

var ContributionSchema	= new Schema({
	date : Date,
	// TCC data
	tcc_country_id : String,
	tcc_country_string : String,
	tcc_un_region : String,
	tcc_un_bloc : String,
	tcc_continent : String,
	tcc_capital : String,
	tcc_capital_loc : {y: Number, x: Number},
	tcc_p5g4a3 : String,
	tcc_sadc : Boolean,
	tcc_eac : Boolean,
	tcc_oic : Boolean,
	tcc_g8 : Boolean,
	tcc_uma : Boolean,
	tcc_au : Boolean,
	tcc_comesa : Boolean,
	tcc_eu : Boolean,
	tcc_censad : Boolean,
	tcc_ecowas : Boolean,
	tcc_asean : Boolean,
	tcc_gcc : Boolean,
	tcc_g20 : Boolean,
	tcc_oecd : Boolean,
	tcc_eccas : Boolean,
	tcc_shanghai : Boolean,
	tcc_nam : Boolean,
	tcc_cis : Boolean,
	tcc_g77 : Boolean,
	tcc_nato : Boolean,
	tcc_oas : Boolean,
	tcc_igad : Boolean,
	tcc_arabLeague : Boolean,
	// Mission data 
	mission : String,
	mission_country_id : String,
	mission_country : String,
	mission_un_region : String,
	mission_un_bloc : String,
	mission_continent : String,
	mission_hq : String,
	mission_hq_loc : {y: Number, x: Number},
	mission_p5g4a3 : String,
	mission_sadc : Boolean,
	mission_eac : Boolean,
	mission_oic : Boolean,
	mission_g8 : Boolean,
	mission_uma : Boolean,
	mission_au : Boolean,
	mission_comesa : Boolean,
	mission_eu : Boolean,
	mission_censad : Boolean,
	mission_ecowas : Boolean,
	mission_asean : Boolean,
	mission_gcc : Boolean,
	mission_g20 : Boolean,
	mission_oecd : Boolean,
	mission_eccas : Boolean,
	mission_shanghai : Boolean,
	mission_nam : Boolean,
	mission_cis : Boolean,
	mission_g77 : Boolean,
	mission_nato : Boolean,
	mission_oas : Boolean,
	mission_igad : Boolean,
	mission_arabLeague : Boolean,
	// Contribution data
	fpu_f : Number,
	fpu_m : Number,
	fpu : Number,
	ip_f : Number,
	ip_m : Number,
	ip : Number,
	eom_f : Number,
	eom_m : Number,
	eom : Number,
	troops_f : Number,
	troops_m : Number,
	troops : Number,
	civpol : Number,
	observers : Number,
	total_f : Number,
	total_m : Number,
	total : Number
});

var collectionName = 'contributions';
module.exports		= mongoose.model('contribution', ContributionSchema, collectionName);